# Generated by Django 4.0.4 on 2022-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forever', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='forever/home/%y')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.TextField(max_length=800),
        ),
    ]
