# Generated by Django 4.0.4 on 2022-10-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forever', '0002_home_alter_video_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='description',
        ),
    ]
