# Generated by Django 4.0.4 on 2022-10-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forever', '0003_remove_home_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Homee',
        ),
    ]
