# Generated by Django 4.0.4 on 2022-10-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forever', '0004_rename_home_homee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homee',
            old_name='title',
            new_name='caption',
        ),
    ]
