# Generated by Django 4.0.4 on 2022-10-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forever', '0005_rename_title_homee_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homee',
            name='caption',
            field=models.TextField(),
        ),
    ]
