# Generated by Django 4.0.4 on 2022-10-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forever', '0006_alter_homee_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='homee',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
