# Generated by Django 4.0.4 on 2022-10-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forever', '0007_homee_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
